#!/bin/bash

function test {
    echo "Test $1"
    $1
    echo "OK"
}

function assert_equal {
    if [[ "$1" != "$2" ]]; then
        echo "Error in (${FUNCNAME[1]} ${BASH_SOURCE[1]}:${BASH_LINENO[0]}):"
        echo "       got: $1"
        echo "  expected: $2"
        exit 1
    fi
}

function assert_true {
    if [[ "$1" != True ]]; then
        echo "Error in (${FUNCNAME[1]} ${BASH_SOURCE[1]}:${BASH_LINENO[0]}), $1 is not True"
        exit 1
    fi
}
