#!/bin/bash

function test {
	$1
	echo "Test $1 - OK"
}

function assert_equal {
	if [[ "$1" != "$2" ]]; then
		echo "Error in ${FUNCNAME[1]}, $1 is not equal to $2"
		exit 1
	fi
}

function assert_true {
	if [[ "$1" != True ]]; then
		echo "Error in ${FUNCNAME[1]}, $1 is not True"
		exit 1
	fi
}
