#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "ScaleIO MDM config changed"

cluster_count=`leader-get cluster_count`
mdm_ips=`leader-get mdm_ips`
slave_names=`leader-get slave_names`
tb_names=`leader-get tb_names`

cluster_mode=`config-get cluster-mode`

if [ $cluster_mode -eq 3 ]
then
	cluster-cmd "class { 'scaleio::cluster': 
	cluster_mode=>'$cluster_mode', slave_names=>'$slave_names', tb_names=>'$tb_names' }"
	juju-log "ScaleIO 3-node cluster is created - ips: $mdm_ips"
fi

	
