#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "ScaleIO MDM config changed"

leader=`is-leader`

# Check if cluster should be resized
if [ -n "$leader" ] && [[ $leader == 'True' ]]; then
	juju-log "Request to check and resize cluster because of config changed"
	resize-cluster
fi
