#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "ScaleIO MDM installing"

apt-get install -y puppet
puppet module install --force puppetlabs-firewall
puppet module install --force puppetlabs-stdlib

server-cmd "class { 'scaleio::mdm_server': is_manager=>1 }"	

juju-log "ScaleIO MDM installed"
