#!/bin/bash
if [ -z "$my_dir" ]; then my_dir="$(dirname "$0")"; fi

# this will be removed in the future
$my_dir/common-temp

. "$my_dir/common"

juju-log "ScaleIO MDM installing: $MY_NAME, $MY_INTERNAL_IP"

if ! puppet --version ; then
  apt-get install -qqfy puppet
fi
puppet module install --version "<1.1.0" cloudscaling-scaleio || /bin/true

server-cmd "class { 'scaleio::mdm_server': }"

juju-log "ScaleIO MDM installed"

status-set waiting "Awaiting ScaleIO cluster creation"
