#!/bin/bash
if [ -z "$my_dir" ]; then my_dir="$(dirname "$0")"; fi
. "$my_dir/common-cluster"

juju-log "ScaleIO leader-settings-changed" 

# Check if some node's departed so the node has to clear the signaling alert flag
if [ -n "`leader-get departing_nodes`" ]; then
    relation-set -r $scaleio_cluster_rid departing_nodes= ;
fi

# Check if cluster reduction is in place and the node needs to reveal its role
reducing_cluster=`leader-get reducing_cluster`
if [ -n "${reducing_cluster}" ] && [ -n "${cluster_nodes[*]+x}" ] && [ -n "${cluster_nodes[$JUJU_UNIT_NAME]+x}" ]; then 
    status-set blocked "Cluster member with a role ${cluster_nodes[$JUJU_UNIT_NAME]} - $reducing_cluster"
    exit
fi

status-set active

check-and-set-role
