#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

# Cluster configuration parameters (all lists are comma-separated with a traling comma after last element):
# mdm_ips - current MDM IPs of the active cluster nodes
# cluster_mode - current cluster mode (1|3|5)
# tbs - active cluster MDM tiebreakers list (including non-ready standbies)
# managers - active cluster MDM managers list (including non-ready standbies)
# tbs_ready - ready standby tiebreakers list
# managers_ready - ready standby managers list
# standby_ips - list of standby managers IPs (to be added to MDM IPs when becoming active cluster member)
# tbs_standby - list of standby tiebreakers including non-ready
# managers_standby - list of standby managers including non-ready
# tbs_leaving - departed tiebreakers (to be removed during cluster resizing)
# managers_leaving - departed managers (to be removed during cluster resizing)
# ips_leaving - IPs of departed members

juju-log "ScaleIO leader elected"

# Init cluster configuration
cluster_mode=`leader-get cluster_mode`
if [ -z "$cluster_mode" ]; then
	leader-set mdm_ips="$MY_IP," cluster_mode=1 tbs='' managers="$MY_NAME," \
		tbs_ready='' managers_ready='' standby_ips='' tbs_standby='' managers_standby='' \
		tbs_leaving='' managers_leaving='' ips_leaving=''
	juju-log "ScaleIO single-node cluster creating (name: $MY_NAME, ip: $MY_IP)"
	server-cmd "class { 'scaleio::mdm_server': master_mdm_name=>'$MY_NAME', mdm_ips=>'$MY_IP', is_manager=>1 }"
	juju-log "ScaleIO single-node cluster created"
	server-cmd "scaleio::login { 'first login': password=>'admin' }"
	server-cmd "scaleio::cluster { 'cluster': password=>'admin', new_password=>'$MY_PASSWORD' }"
	juju-log "ScaleIO cluster password changed"
	
	status-set active
	
	# Notify MDMs which joined before leader's got elected
	rids=`relation-ids scaleio-mdm`
	juju-log "ScaleIO MDM elected leader rids of MDMs: $rids"
	if [ -n "$rids" ]; then
		juju-log "ScaleIO MDM elected leader notifies MDMs: $rids"
		for rid in $( rids ); do
			relation-set -r $rid notify=true
	    done
	fi
fi
