#!/bin/bash
if [ -z "$my_dir" ]; then my_dir="$(dirname "$0")"; fi
. "$my_dir/common-cluster"

juju-log "ScaleIO leader-settings-changed" 

if [ -z "${ordered_nodes[*]+x}" ] || [ -z ${ordered_nodes["$JUJU_UNIT_NAME"]+x} ] ; then exit; fi
ordered_role=${ordered_nodes["$JUJU_UNIT_NAME"]}
if [[ $ordered_role == manager ]]; then
	is_manager=1
	relation-set -r $scaleio_cluster_rid management_ip=$MY_MANAGEMENT_IP
else
	is_manager=0
fi
# Remove it from list of standbies first, just in case error occurred in previous cluster adjustments
# cluster-cmd "scaleio::mdm { 'remove from cluster': name=>'$MY_NAME', ensure=>'absent' }"
server-cmd "class { 'scaleio::mdm_server': is_manager=>$is_manager }"
relation-set -r $scaleio_cluster_rid role=$ordered_role
status-set active
juju-log "ScaleIO MDM $MY_NAME changed role to $ordered_role"
