#!/bin/bash
if [ -z "$my_dir" ]; then my_dir="$(dirname "$0")"; fi
. "$my_dir/common-cluster"

juju-log "ScaleIO leader-settings-changed" 

# Check if some node's departed so the node has to clear the signaling alert flag
if [ -n "`leader-get departing_nodes`" ]; then
    relation-set -r $scaleio_cluster_rid departing_nodes= ;
fi

# Check if cluster reduction is in place and the node needs to reveal its role
reducing_cluster=`leader-get reducing_cluster`
if [ -n "${reducing_cluster}" ] && [ -n "${cluster_nodes[*]+x}" ] && [ -n "${cluster_nodes[$JUJU_UNIT_NAME]+x}" ]; then 
    status-set blocked "Cluster member with a role ${cluster_nodes[$JUJU_UNIT_NAME]} - $reducing_cluster"
    exit
fi
  
# Check if this node is ordered to change role
if [ -n "${ordered_nodes[*]+x}" ] && [ -n "${ordered_nodes[$JUJU_UNIT_NAME]+x}" ]; then
    # This node is ordered to change role
    ordered_role=${ordered_nodes["$JUJU_UNIT_NAME"]}
    if [[ $ordered_role == manager ]]; then
        is_manager=1
        relation-set -r $scaleio_cluster_rid management_ip=$MY_MANAGEMENT_IP
    else
        is_manager=0
    fi
    # Remove it from list of standbies first, just in case error occurred in previous cluster adjustments
    cluster-cmd "scaleio::mdm { 'remove from cluster': name=>'$MY_NAME', ensure=>'absent' }"
    server-cmd "class { 'scaleio::mdm_server': is_manager=>$is_manager }"
    relation-set -r $scaleio_cluster_rid role=$ordered_role
    status-set waiting "Waiting to become cluster member with a role ${ordered_role}"
    juju-log "ScaleIO MDM $MY_NAME changed role to $ordered_role"
    exit
fi

status-set active
