#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "ScaleIO leader elected"

# Init cluster configuration
cluster_mode=`leader-get cluster_mode`
if [ -z "$cluster_mode" ]; then
	leader-set ready_standbies=" " mdm_ips=$MY_IP manager_count=0 tb_count=0 cluster_mode=1
	juju-log "ScaleIO single-node cluster creating (name: $MY_NAME, ip: $MY_IP)"
	server-cmd "class { 'scaleio::mdm_server': master_mdm_name=>'$MY_NAME', mdm_ips=>'$MY_IP', is_manager=>1 }"
	juju-log "ScaleIO single-node cluster created"
	server-cmd "scaleio::login { 'first login': password=>'admin' }"
	server-cmd "scaleio::cluster { 'cluster': password=>'admin', new_password=>'$MY_PASSWORD' }"
	juju-log "ScaleIO cluster password changed"
	
	status-set active
	
	# Notify MDMs which joined before leader's got elected
	rids=`relation-ids scaleio-mdm`
	juju-log "ScaleIO MDM elected leader rids of MDMs: $rids"
	if [ -n "$rids" ]; then
		juju-log "ScaleIO MDM elected leader notifies MDMs: $rids"
		for rid in $( rids ); do
			relation-set -r $rid notify=true
	    done
	fi
fi
