#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

# Cluster configuration parameters (all lists are comma-separated with a traling comma after last element):
# mdm_internal_ips - current MDM internal IPs of the active cluster nodes
# mdm_management_ips - current MDM management IPs of the active cluster nodes
# cluster_mode - current cluster mode (1|3|5)
# tbs - active cluster MDM tiebreakers list (including non-ready standbies)
# managers - active cluster MDM managers list (including non-ready standbies)
# tbs_ready - ready standby tiebreakers list
# managers_ready - ready standby managers list
# standby_internal_ips - list of standby managers internal IPs (to be added to MDM IPs when becoming active cluster member)
# standby_management_ips - list of standby managers management IPs (to be added to MDM IPs when becoming active cluster member)
# tbs_standby - list of standby tiebreakers including non-ready
# managers_standby - list of standby managers including non-ready
# tbs_leaving - departed tiebreakers (to be removed during cluster resizing)
# managers_leaving - departed managers (to be removed during cluster resizing)
# internal_ips_leaving - internal IPs of departed members
# management_ips_leaving - management IPs of departed members
# sdcs_ready - IPs of ready SDCs

juju-log "ScaleIO leader elected"

# Init cluster configuration
cluster_mode=`leader-get cluster_mode`
if [ -z "$cluster_mode" ]; then
	leader-set mdm_internal_ips="$MY_INTERNAL_IP," mdm_management_ips="$MY_MANAGEMENT_IP," \
		cluster_mode=1 tbs='' managers="$MY_NAME," \
		tbs_ready='' managers_ready='' standby_internal_ips='' standby_management_ips='' tbs_standby='' managers_standby='' \
		tbs_leaving='' managers_leaving='' internal_ips_leaving='' management_ips_leaving=''
	juju-log "ScaleIO single-node cluster creating (name: $MY_NAME, internal_ip: $MY_INTERNAL_IP, management_ip: $MY_MANAGEMENT_IP)"
	server-cmd "class { 'scaleio::mdm_server': master_mdm_name=>'$MY_NAME', mdm_ips=>'$MY_INTERNAL_IP', is_manager=>1, mdm_management_ips=>'$MY_MANAGEMENT_IP' }"
	juju-log "ScaleIO single-node cluster created"
	server-cmd "scaleio::login { 'first login': password=>'admin' }"
	server-cmd "scaleio::cluster { 'cluster': password=>'admin', new_password=>'$MY_PASSWORD' }"
	juju-log "ScaleIO cluster password changed"
	leader-set password=$MY_PASSWORD
	
	status-set active
	
	# Notify MDMs which joined before leader's got elected
	rids=`relation-ids scaleio-mdm`
	juju-log "ScaleIO MDM elected leader rids of MDMs: $rids"
	if [ -n "$rids" ]; then
		juju-log "ScaleIO MDM elected leader notifies MDMs: $rids"
		for rid in $( echo $rids ); do
			relation-set -r $rid notify=true
	    done
	fi
fi
