#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

log-relation "ScaleIO SDC or GW joined"

leader=`is-leader`
if [[ "$leader" != 'True' ]]; then exit; fi

ips=`leader-get mdm_internal_ips`
relation-set mdm_internal_ips=$ips

ips=`leader-get mdm_management_ips`
relation-set mdm_management_ips=$ips

# propagate sdcs_ready to GW
sdcs_ready=`leader-get sdcs_ready`
relation-set sdcs_ready=$sdcs_ready
# propogate admin password to GW
password=`config-get password`
relation-set password=$password
# propogate client password to GW
client_password=`leader-get client_password`
relation-set client_password=$client_password
