#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

log-relation "ScaleIO Standby MDM joining"

remote_name=$(convert-name $JUJU_REMOTE_UNIT)
remote_ip=`relation-get private-address`
leader=`is-leader`
mdm_ips=`leader-get mdm_ips`
cluster_count=`leader-get cluster_count`

if [ $leader == 'True' ]; then
	role=`leader-get role_$remote_name`
	state=`relation-get state_$remote_name`
else
	role=`leader-get role_$MY_NAME`
	state=`relation-get state_$MY_NAME`
fi
if [ -z "$state" ]; then
  state='unknown'
fi

juju-log "STATE AND ROLE in $MY_NAME: $role, $state"

if [ $leader == 'True' ] ; then
  log-relation "ScaleIO cluster-relation-changed, leader-side"
  if [ $state == 'installed' ] ; then
    cluster-cmd "class { 'scaleio::mdm': name=>'$remote_name', ips=>'$remote_ip', role=>'$role' }"
    status-set active
    juju-log "ScaleIO Standby MDM $remote_name added as $role"
    juju-log "ScaleIO Cluster stats - cluster_count: $cluster_count, ips: $mdm_ips"
    if [ $role == 'manager' ] ; then
      mdm_ips="$mdm_ips,$remote_ip"
      leader-set mdm_ips=$mdm_ips
    fi
  fi
else
  log-relation "ScaleIO cluster-relation-changed, slave-side" 
  if [ $state == 'ordered' ]; then
  	if [ $role == 'tb' ]; then
  		is_manager=0
  	else
  		is_manager=1
  	fi
    server-cmd "class { 'scaleio::mdm_server': is_manager=>$is_manager }"
	relation-set state_$MY_NAME=installed
    status-set active
    juju-log "ScaleIO MDM $MY_NAME changed role to $role"
  fi
fi
