#!/bin/bash
if [ -z "$my_dir" ]; then my_dir="$(dirname "$0")"; fi
. "$my_dir/common-cluster"

status=`status-get`
if [ $status == 'terminated' ]; then exit; fi

# Let go a departing MDMs and adjust counters
if [ `is-leader` == 'True' ]; then
	# New code
	juju-log "ScaleIO MDM departing"
	
	# Invalidating current ordered tbs and managers if any
	leader-set ordered_nodes=

	DEPARTING_NODE=$JUJU_REMOTE_UNIT
	adjust-cluster
fi
