#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

leader=`is-leader`
if [[ "$leader" != 'True' ]] ; then exit; fi

remote_name=$(convert-name $JUJU_REMOTE_UNIT)
log-relation "ScaleIO SDS $remote_name departing"

# TODO: Workaround for non-working cluster when 3 goes to 1. During MDM service removal the following will fail	
set +e
FACTER_mdm_ips=$MY_MDMS puppet apply -e "scaleio::login {'login': password=>'$MY_PASSWORD'} -> \
  scaleio::sds { 'sds $remote_name': sio_name=>'$remote_name', ensure=>'absent' }"
set -e

log-relation "ScaleIO SDS $remote_name departed"
