#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

log-relation "ScaleIO SDC or GW joined"

leader=`is-leader`
if [[ $leader != 'True' ]]; then exit; fi

ips=`leader-get mdm_internal_ips`
relation-set mdm_internal_ips=$ips

ips=`leader-get mdm_management_ips`
relation-set mdm_management_ips=$ips
