#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

log-relation "ScaleIO Standby MDM joining"

leader=`is-leader`
mdm_ips=`leader-get mdm_ips`
slave_names=`leader-get slave_names`
tb_names=`leader-get tb_names`
remote_name=${JUJU_REMOTE_UNIT/\//-} 
remote_ip=`relation-get private-address`

if [ $leader == 'True' ] 
then
	cluster_count=`leader-get cluster_count`
	juju-log "ScaleIO cluster count: $cluster_count"

	is_manager=$((cluster_count % 2))
	relation-set is_manager=$is_manager
	if (( is_manager == 1 ))
	then
		role="manager"
		slave_names="$remote_name"
		leader-set slave_names=$slave_names
	else
		role="tb"
		tb_names="$remote_name"
		leader-set tb_names=$tb_names			
	fi
	((cluster_count++))
	leader-set cluster_count=$cluster_count
	relation-set mdm_role=$role
	
	juju-log "ScaleIO Standby MDM joining: $remote_name, $role"
	juju-log "ScaleIO cluster count and ips: $cluster_count, $mdm_ips"
fi
