#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

log-relation "ScaleIO SDS relation changing"

remote_name=$(convert-name $JUJU_REMOTE_UNIT)
remote_internal_ip=`relation-get sds_internal_ip_$remote_name`
remote_storage_ip=`relation-get sds_storage_ip_$remote_name`
protection_domain=`relation-get protection_domain`
fault_set=`relation-get fault_set`
storage_pools=`relation-get storage_pools`
device_paths=`relation-get device_paths`
leader=`is-leader`

if [[ -z "$protection_domain" || "$leader" != 'True' ]]; then exit; fi

if [ -n "$remote_storage_ip" ] ; then
  ips="$remote_internal_ip,$remote_storage_ip"
  ip_roles='sds_only,sdc_only'
else
  ips="$remote_internal_ip"
  ip_roles='all'
fi

cluster-cmd "scaleio::protection_domain { 'protection domain $protection_domain': 
  name=>'$protection_domain', fault_sets=>[$fault_set], storage_pools=>[$storage_pools] }"

performance_profile=`config-get performance-profile`
cluster-cmd "scaleio::sds { 'sds $remote_name':
  name=>'$remote_name', ips=>'$ips', ip_roles=>'$ip_roles', protection_domain=>'$protection_domain', \
  fault_set=>'$fault_set', storage_pools=>'$storage_pools', device_paths=>'$device_paths',
  performance_profile=>'$performance_profile' }"

log-relation "ScaleIO SDS relation changed"
