#!/bin/bash
if [ -z "$my_dir" ]; then my_dir="$(dirname "$0")"; fi
. "$my_dir/common"

log-relation "ScaleIO Standby MDM joining"
relation-set internal_ip=$MY_INTERNAL_IP

my_state=`relation-get state $JUJU_UNIT_NAME`

if [ $leader != 'True' ]; then
	state=`relation-get role`
	if [ -z "$role" ]; then
		# Newcomer status initialization
		status-set blocked "ScaleIO MDM is waiting to join cluster"
		relation-set role=none
	fi
else
	if [ -z "$role" ]; then
		# Initial master first role initialization - couldn't be done earlier because no relation existed
		# We don't care that it's actually master - all non-tiebreakers are current or potential slaves
		relation-set role=slave
	fi	
fi
