#!/usr/bin/python

"""Amulet tests on a basic keystone deployment on trusty-mitaka."""

from basic_deployment import KeystoneBasicDeployment

if __name__ == '__main__':
    deployment = KeystoneBasicDeployment(series='trusty',
                                         openstack='cloud:trusty-mitaka',
                                         source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
