#!/usr/bin/python

"""Amulet tests on a basic keystone deployment on xenial-mitaka."""

from basic_deployment import KeystoneBasicDeployment

if __name__ == '__main__':
    deployment = KeystoneBasicDeployment(series='xenial')
    deployment.run_tests()
