#!/bin/bash

# TODO: remove when packages will be in official repo
apt_repo=`config-get scaleio-apt-repo`
if [ -n "$apt_repo" ] ; then
  if wget -t 2 -T 30 -q --output-document=/root/repo.key $apt_repo/repo.key ; then
    apt-key add /root/repo.key
  fi

  cat 2>/dev/null <<EOF > /etc/apt/sources.list.d/repo.list
deb $apt_repo/ubuntu trusty main
deb-src $apt_repo/ubuntu trusty main
EOF
fi
