#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "ScaleIO SDS config changed"

ftp=`config-get scaleio-driver-ftp`
if [ -n "$ftp" ] ; then
  server-cmd "class { 'scaleio::sds_server': drv_src=>'$ftp' }"
fi

relation-set-all
