#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "Installing ScaleIO SDS server"

apt-get install -y puppet

server-cmd "class { 'scaleio::sds_server': }"	

juju-log "Installed ScaleIO SDS server"
