#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "ScaleIO SDS installing"

apt-get install -y puppet
puppet module install puppetlabs-firewall
puppet module install puppetlabs-stdlib

server-cmd "class { 'scaleio::sds_server': }"	

juju-log "ScaleIO SDS installed"
