#!/usr/bin/python

"""Amulet tests on a basic nova compute deployment on trusty-liberty."""

from basic_deployment import NovaBasicDeployment

if __name__ == '__main__':
    deployment = NovaBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-liberty',
                                     source='cloud:trusty-updates/liberty')
    deployment.run_tests()
