#!/usr/bin/python

"""Amulet tests on a basic nova compute deployment on trusty-mitaka."""

from basic_deployment import NovaBasicDeployment

if __name__ == '__main__':
    deployment = NovaBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-mitaka',
                                     source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
