#!/usr/bin/python

"""Amulet tests on a basic nova compute deployment on wily-liberty."""

from basic_deployment import NovaBasicDeployment

if __name__ == '__main__':
    deployment = NovaBasicDeployment(series='wily')
    deployment.run_tests()
