#!/usr/bin/python

"""Amulet tests on a basic nova compute deployment on xenial-mitaka."""

from basic_deployment import NovaBasicDeployment

if __name__ == '__main__':
    deployment = NovaBasicDeployment(series='xenial')
    deployment.run_tests()
