#!/bin/bash
my_dir="$(dirname "$0")"

# this will be removed in the future
$my_dir/common-temp

. "$my_dir/common"

juju-log "ScaleIO for OpenStack module installed"

#status-set waiting "Awaiting relation to scaleio-gw"
status-set active
