#!/bin/bash
my_dir="$(dirname "$0")"

. "$my_dir/common"

juju-log "ScaleIO for OpenStack module installing"

apt-get install -qqfy puppet
puppet module install --version "<1.1.0" --force cloudscaling-scaleio_openstack

juju-log "ScaleIO for OpenStack module installed"

status-set waiting "Awaiting relation to scaleio-gw"
