#!/bin/bash
my_dir="$(dirname "$0")"

juju-log "ScaleIO for OpenStack module installing"
apt-get -qq update

. "$my_dir/common"

if ! puppet --version ; then
  apt-get install -qqfy puppet
fi
puppet module install --version "<1.2.0" cloudscaling-scaleio_openstack || /bin/true

status-set waiting "Awaiting relation to scaleio-gw"

juju-log "ScaleIO for OpenStack module installed"
