#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "ScaleIO OpenStack integration removing"	

server-cmd "class { 'scaleio_openstack::nova': ensure=>absent }"
server-cmd "class { 'scaleio_openstack::cinder': ensure=>absent }"

juju-log "ScaleIO GW removed"
