#!/bin/bash

apt-get install -y puppet
puppet module install --version "<1.1.0" cloudscaling-scaleio --module_repository https://forge.puppet.com/

# TODO: remove when packages will be in official repo
apt_repo=`config-get scaleio-apt-repo`
if [ -n "$apt_repo" ] ; then
  if wget -q --output-document=/root/repo.key $apt_repo/repo.key ; then
    apt-key add /root/repo.key
  fi

  cat 2>/dev/null <<EOF > /etc/apt/sources.list.d/repo.list
deb $apt_repo/ubuntu trusty main
deb-src $apt_repo/ubuntu trusty main
EOF

  apt-get -qq update
fi
