#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "ScaleIO GW config changed"

rid=`relation-ids scaleio-openstack`
if [ -z "$rid" ]; then exit; fi
relation-set -r $rid password=$(config-get password)
