#!/bin/bash
my_dir="$(dirname "$0")"

# this will be removed in the future
$my_dir/common-temp

juju-log "ScaleIO GW installing"
apt-get -qq update

. "$my_dir/common"

if ! puppet --version ; then
  apt-get install -qqfy puppet
fi
puppet module install --version "<1.2.0" cloudscaling-scaleio || /bin/true

api_port=$(get-port)
server-cmd "class { 'scaleio::gateway_server': port=>'$api_port' }"

juju-log "ScaleIO GW installed"

status-set waiting "Awaiting relation with scaleio-mdm"
