#!/bin/bash
my_dir="$(dirname "$0")"

# this will be removed in the future
$my_dir/common-temp

. "$my_dir/common"

juju-log "ScaleIO GW installing"

password=`config-get password`
server-cmd "class { 'scaleio::gateway_server': password=>'$password' }"

juju-log "ScaleIO GW installed"

status-set waiting "Awaiting relation with scaleio-mdm"
