#!/bin/bash
my_dir="$(dirname "$0")"

juju-log "ScaleIO GW installing"
apt-get -qq update

. "$my_dir/common"

if ! puppet --version ; then
  apt-get install -qqfy puppet
fi
puppet module install --version "<1.3.0" cloudscaling-scaleio || /bin/true

api_port=$(get-port)
scaleio_packages_url=$(config-get scaleio-packages-url)
if [[ -z "$scaleio_packages_url" ]] ; then
  juju-log -l 'ERROR' "URL for packages absent. Can't install ScaleIO."
  exit 1
fi
server-cmd "class { 'scaleio::gateway_server': port=>'$api_port', pkg_ftp=>'$scaleio_packages_url' }"

juju-log "ScaleIO GW installed"

status-set waiting "Awaiting relation with scaleio-mdm"
