#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

log-relation "ScaleIO client joining"

if [ $(is-leader) == 'True' ] ; then
    relation-set client_password=$(leader-get client_password)
    relation-set port=$(config-get port)
    relation-set ip=$(get-ip)
    relation-set sdcs_ready=$(leader-get sdcs_ready)
fi
