#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

log-relation "ScaleIO MDM relation changing for ScaleIO Gateway"

mdm_management_ips=`relation-get mdm_management_ips`

if [ -z "$mdm_management_ips" ]; then exit; fi

log-relation "ScaleIO Gateway setting up mdm_ips to $mdm_management_ips"
server-cmd "class { 'scaleio::gateway_server': mdm_ips=>'$mdm_management_ips' }"

status-set active

log-relation "ScaleIO MDM changed for ScaleIO Gateway"
