#!/bin/bash
my_dir="$(dirname "$0")"

# this will be removed in the future
. $my_dir/common-temp

. $my_dir/common

juju-log "ScaleIO GUI installing"

server-cmd "class { 'scaleio::gui_server': }"

status-set active

juju-log "ScaleIO GUI installed"
