#!/bin/bash
my_dir="$(dirname "$0")"

# this will be removed in the future
. $my_dir/common-temp

juju-log "ScaleIO GUI installing"
apt-get -qq update

. $my_dir/common

if ! puppet --version ; then
  apt-get install -qqfy puppet
fi
puppet module install --version "<1.2.0" cloudscaling-scaleio || /bin/true

scaleio_packages_url=$(config-get scaleio-packages-url)
if [[ -z "$scaleio_packages_url" ]] ; then
  juju-log -l 'ERROR' "URL for packages absent. Can't install ScaleIO."
  exit 1
fi
server-cmd "class { 'scaleio::gui_server': pkg_src=>'$scaleio_packages_url'}"

status-set active

juju-log "ScaleIO GUI installed"
