#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

log-relation "ScaleIO MDM joining"

remote_name=$(convert-name $JUJU_REMOTE_UNIT)
remote_ip=`relation-get private-address`

if [ -z "$remote_ip" ]; then exit; fi

server-cmd "class { 'scaleio::sdc_server': mdm_ip=>'$remote_ip' }"

log-relation "ScaleIO MDM joined"
