#!/bin/bash
my_dir="$(dirname "$0")"
set -eu

function convert-name {
  echo ${1//[-\/]/_}
}

function log-relation {
  local remote_name=$(convert-name $JUJU_REMOTE_UNIT)
  local remote_ip=`relation-get private-address`
  juju-log "$1: $remote_name, $remote_ip"
}

function get_mdm_ips() {
  local ip=$(config-get gateway-ip)
  local port=$(config-get gateway-port)
  local user=$(config-get client-user)
  local password=$(config-get client-password)

  local gw_url="https://$ip:$port/api"

  token=`curl -k -u $user:$password $gw_url/login 2>/dev/null | xargs`
  if [[ -z "$token" ]] ; then
    return 1
  fi
  ips=`curl -k -u $user:$token $gw_url/Configuration 2>/dev/null | sed -e 's/.*"mdmAddresses":\[\([\"\.0-9,]*\)\].*/\1/' | sed -e 's/\"//g' | xargs`
  if [[ -z "$ips" ]] ; then
    return 1
  fi
  echo $ips
}
