#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "ScaleIO Cluster config changed"

if ! ips=`get_mdm_ips` ; then
  status-set blocked "Could not connect to ScaleIO cluster"
  ips=''
else
  status-set active
fi

rids=`relation-ids scaleio-mdm`
for rid in $rids ; do
  relation-set -r $rid mdm_internal_ips=$ips
done

ip=$(config-get gateway-ip)
port=$(config-get gateway-port)
user=$(config-get gateway-user)
password=$(config-get gateway-password)

rids=`relation-ids scaleio-gw`
for rid in $rids ; do
  relation-set -r $rid port=$port
  relation-set -r $rid ip=$ip
  relation-set -r $rid client_user=$user
  relation-set -r $rid client_password=$password
done
