#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

if ! ips=`get_mdm_ips` ; then
  status-set blocked "Could not connect to ScaleIO cluster"
  ips=''
fi

rids=`relation-ids scaleio-mdm`
for rid in $rids ; do
  relation-set -r $rid mdm_internal_ips=$ips
done
