#!/bin/bash
my_dir="$(dirname "$0")"

# this will be removed in the future
$my_dir/common-temp

juju-log "ScaleIO SDC installing"
apt-get -qq update

. "$my_dir/common"

if ! puppet --version ; then
  apt-get install -qqfy puppet
fi
puppet module install --version "<1.1.0" cloudscaling-scaleio || /bin/true

ftp=`config-get scaleio-driver-ftp`
server-cmd "class { 'scaleio::sdc_server': ftp=>'$ftp' }"

status-set waiting "Awaiting relation to scaleio-mdm"

juju-log "ScaleIO SDC installed"
