#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "ScaleIO SDC installing"

status-set maintenance

apt-get install -y puppet
puppet module install --force puppetlabs-firewall
puppet module install --force puppetlabs-stdlib

server-cmd "class { 'scaleio::sdc_server': }"	

juju-log "ScaleIO SDC installed"
