#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

log-relation "ScaleIO MDM joining"

mdm_ips=`relation-get mdm_ips`

if [ -z "$mdm_ips" ]; then exit; fi

server-cmd "class { 'scaleio::sdc_server': mdm_ip=>'$mdm_ips' }"

status-set active

relation-set ready='true'
juju-log "ScaleIO SDC reporting it's ready"

log-relation "ScaleIO MDM joined, mdm IPs are $mdm_ips"
