#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

log-relation "ScaleIO MDM departed"

status-set waiting "Awaiting relation to scaleio-mdm"

server-cmd "class { 'scaleio::sdc_server': mdm_ip=>'', ftp=>'' }"

relation-set ready='false'
