#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

log-relation "ScaleIO MDM joining"

mdm_internal_ips=`relation-get mdm_internal_ips`

if [ -z "$mdm_internal_ips" ]; then
  server-cmd "class { 'scaleio::sdc_server': ensure_properties=>'absent', drv_src=>'' }"
  exit
fi

server-cmd "class { 'scaleio::sdc_server': mdm_ip=>'$mdm_internal_ips', drv_src=>'' }"

status-set active

relation-set ready='true'
juju-log "ScaleIO SDC reporting it's ready"

log-relation "ScaleIO MDM joined, mdm IPs are $mdm_internal_ips"
