#!/usr/bin/python

"""Amulet tests on a basic cinder deployment on precise-icehouse."""

from basic_deployment import CinderBasicDeployment

if __name__ == '__main__':
    deployment = CinderBasicDeployment(series='precise',
                                         openstack='cloud:precise-icehouse',
                                         source='cloud:precise-updates/icehouse')
    deployment.run_tests()
