#!/usr/bin/python

"""Amulet tests on a basic Cinder deployment on trusty-icehouse."""

from basic_deployment import CinderBasicDeployment

if __name__ == '__main__':
    deployment = CinderBasicDeployment(series='trusty')
    deployment.run_tests()
