#!/usr/bin/python

"""Amulet tests on a basic cinder deployment on trusty-kilo."""

from basic_deployment import CinderBasicDeployment

if __name__ == '__main__':
    deployment = CinderBasicDeployment(series='trusty',
                                       openstack='cloud:trusty-kilo',
                                       source='cloud:trusty-updates/kilo')
    deployment.run_tests()
