#!/usr/bin/python

"""Amulet tests on a basic cinder deployment on trusty-liberty."""

from basic_deployment import CinderBasicDeployment

if __name__ == '__main__':
    deployment = CinderBasicDeployment(series='trusty',
                                       openstack='cloud:trusty-liberty',
                                       source='cloud:trusty-updates/liberty')
    deployment.run_tests()
