#!/usr/bin/python

"""Amulet tests on a basic cinder deployment on trusty-mitaka."""

from basic_deployment import CinderBasicDeployment

if __name__ == '__main__':
    deployment = CinderBasicDeployment(series='trusty',
                                       openstack='cloud:trusty-mitaka',
                                       source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
