#!/usr/bin/python

"""Amulet tests on a basic Cinder deployment on xenial-mitaka."""

from basic_deployment import CinderBasicDeployment

if __name__ == '__main__':
    deployment = CinderBasicDeployment(series='xenial')
    deployment.run_tests()
