#!/usr/bin/python

"""Amulet tests on a basic Cinder git deployment on trusty-icehouse."""

from basic_deployment import CinderBasicDeployment

if __name__ == '__main__':
    deployment = CinderBasicDeployment(series='trusty', git=True)
    deployment.run_tests()
