#!/usr/bin/python

"""Amulet tests on a basic Cinder git deployment on trusty-juno."""

from basic_deployment import CinderBasicDeployment

if __name__ == '__main__':
    deployment = CinderBasicDeployment(series='trusty',
                                       openstack='cloud:trusty-juno',
                                       source='cloud:trusty-updates/juno',
                                       git=True)
    deployment.run_tests()
